### ISSUE TITLE
treesit-query-error when using eglot with vls

### ISSUE THREAD

**Issue by wakira** [theschmocker/vue-ts-mode#1] opened 2023-10-07 00:36 UTC
When eglot is activated, moving the point in the javascript part of Vue files causes the following error and hangs emacs for several seconds:

`error in process filter: Query pattern is malformed: "Cannot find captured node", vue-ts-mode-sfc-tag-face, "A predicate can only refer to captured nodes in the same pattern"`

Stacktrace:

```
Debugger entered--Lisp error: (treesit-query-error "Cannot find captured node" vue-ts-mode-sfc-tag-face "A predicate can only refer to captured nodes in th...")
  treesit-font-lock-fontify-region(1 332 nil)
  font-lock-fontify-syntactically-region(1 332 nil)
  font-lock-default-fontify-region(1 332 nil)
  font-lock-fontify-region(1 332)
  #f(compiled-function (beg end) #<bytecode -0x177bb5eb05636987>)(1 332)
  font-lock-ensure()
  eglot--format-markup((:language "ts" :value "CombinedVueInstance<Vue, {\n    systemDiagram: any;..."))
  eglot--hover-info([(:language "ts" :value "CombinedVueInstance<Vue, {\n    systemDiagram: any;...")] (:start (:line 3605 :character 4) :end (:line 3605 :character 8)))
  #f(compiled-function (jsonrpc-lambda-elem13) #<bytecode -0x19af629ec1b2a680>)((:range (:start (:line 3605 :character 4) :end (:line 3605 :character 8)) :contents [(:language "ts" :value "CombinedVueInstance<Vue, {\n    systemDiagram: any;...")]))
  jsonrpc-connection-receive(#<eglot-lsp-server eglot-lsp-server-1e0e77a> (:jsonrpc "2.0" :id 29 :result (:range (:start (:line 3605 :character 4) :end (:line 3605 :character 8)) :contents [(:language "ts" :value "CombinedVueInstance<Vue, {\n    systemDiagram: any;...")])))
  jsonrpc--process-filter(#<process EGLOT (my-test-project/(vue-ts-mode))> "Content-Length: 501\15\n\15\n{\"jsonrpc\":\"2.0\",\"id\":29,\"r...")
```

When I remove the following query in vue-ts-mode-font-lock-settings the error goes away:

```
   `(((component
       :anchor
       (_
        (_
         (tag_name) @vue-ts-mode-sfc-tag-face
         (:match ,(regexp-opt vue-ts-mode-sfc-tags) @vue-ts-mode-sfc-tag-face))) :*))
```

**Comment by theschmocker** [comment] 2023-10-07 03:44
I'm not too familiar with eglot (I normally use lsp-mode), but hopefully we can figure this out.

When I swap over to eglot, I'm not able to reproduce this.

These lines in the stacktrace stand out to me:
```
eglot--format-markup((:language "ts" :value "CombinedVueInstance<Vue, {\n    systemDiagram: any;..."))
  eglot--hover-info([(:language "ts" :value "CombinedVueInstance<Vue, {\n    systemDiagram: any;...")] (:start (:line 3605 :character 4) :end (:line 3605 :character 8)))
```

Looking into the source code of `eglot--format-markup`, it appears that it looks for `:kind` in the plist passed to it to determine what mode to use to highlight the string returned by the language server:
```elisp
            (if (stringp markup) (list markup 'gfm-view-mode)
                 (list (plist-get markup :value)
                       (pcase (plist-get markup :kind)
                         ("markdown" 'gfm-view-mode)
                         ("plaintext" 'text-mode)
                         (_ major-mode))))
```

I don't see `:kind` in the stacktrace, so my guess is that it's falling back to `major-mode` -- `vue-ts-mode` in this case -- which wouldn't be able to handle the plain TypeScript in `:value`. 

Using the latest version of vue-language-server, I see messages like this in the events buffer displayed by `M-x eglot-events-buffer`:

```
(:jsonrpc "2.0" :id 424 :result
          (:contents
           (:kind "markdown" :value "```typescript\nconst test: DefineComponent<{}, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, {}, string, PublicProps, Readonly<ExtractPropTypes<{}>>, {}>\n```")
           :range
           (:start
            (:line 36 :character 6)
            :end
            (:line 36 :character 10))))
```

Are you using the latest version of [vue-language-server](https://www.npmjs.com/package/@vue/language-server)?

If so, can you provide a minimal example of a Vue component which triggers this error, along with more information about your configuration? Emacs version, eglot version and configuration, etc.

**Comment by wakira** [comment] 2023-10-07 04:42
Ahh, maybe it's simply because I am using [vls(vetur)](https://www.npmjs.com/package/vls) instead...

Will look into this later

**Comment by theschmocker** [comment] 2023-10-07 05:42
I bet that's it!

In my experience, the new Volar-based tooling is a big improvement over Vetur, so if you're able to, I definitely recommend switching to it. 

If you need to stick with vls/vetur, however, I think you could work around this error by advising `eglot--format-markup`. Something along the lines of the following (untested):

```elisp
(defun eglot--format-markup-ensure-kind-advice (args)
  (let ((markup (car args)))
    (list
     (if (or (stringp markup)
             (plist-get markup :kind))
         markup
       (plist-put markup :kind "plaintext")))))

(advice-add #'eglot--format-markup :filter-args #'eglot--format-markup-ensure-kind-advice)
```

Since it seems that this is caused by Emacs attempting to highlight a non-Vue language using `vue-ts-mode`, I'm going to say that this is not a bug in this package and close the issue. Happy to continue the discussion here, though!

**Closed as not planned by theschmocker** 2023-10-07 05:42 UTC

**Comment by theschmocker** [comment] 2023-10-07 05:45
Updated the title to mention vls for visibility in case anyone else encounters the same error
